name: clang-format check
on: [push, pull_request]
permissions:
  contents: read
jobs:
  clang-format:
    name: clang-format check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: clang-format
      uses: jidicula/clang-format-action@v4.14.0
      with:
        clang-format-version: '19'
        check-path: 'Code_Exercises'
        fallback-style: 'Google'
        include-regex: '^.*\.(((c|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))$'
